#!/usr/bin/env python3
"""
offgram — an offline web gallery for an instaloader archive.

A tiny, dependency-free local gallery for an Instagram archive downloaded with
instaloader, with "update" buttons that drive instaloader to fetch new content.
The archive can live anywhere — local disk or a network share.

Run:
    python3 offgram.py        # collection path + login come from config.py
then open http://localhost:8077

Design notes:
  * The whole collection is scanned ONCE in a background thread and cached to a
    LOCAL json file (~/.cache/offgram); pages render from that in-memory index
    and never re-walk the archive — which keeps browsing instant even when the
    files live on a network share.
  * Captions/original-post URLs come from instaloader's '<name>.txt' / '.json.xz'
    sidecars, read lazily when you open an item. Video posters are generated by
    ffmpeg on demand and cached locally.
  * Nothing is ever written to the archive by this tool except via instaloader.
    If this script breaks, your folders are untouched and browsable in Finder.
  * Optional legacy support: if a 4K Stogram '.stogram.sqlite' and/or
    '.thumb.stogram/' folders are present, offgram also reads captions/URLs and
    thumbnails from them. A pure instaloader archive never uses any of this.
"""

import configparser
import html
import http.server
import json
import lzma
import mimetypes
import os
import re
import sqlite3
import subprocess
import sys
import tempfile
import threading
import time
import urllib.parse
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path

# ---------------------------------------------------------------------------
# Config — personal settings (collection path, instaloader login). Resolved in
# priority: env vars OFFGRAM_COLLECTION / OFFGRAM_LOGIN, then a `config.py` found
# in $OFFGRAM_CONFIG, ~/.config/offgram/, the script's dir, or the cwd. See
# config.example.py. OFFGRAM_PORT overrides the port.
# ---------------------------------------------------------------------------
def _load_config():
    import importlib.util
    collection = os.environ.get("OFFGRAM_COLLECTION", "")
    login = os.environ.get("OFFGRAM_LOGIN", "")
    paths = []
    if os.environ.get("OFFGRAM_CONFIG"):
        paths.append(Path(os.environ["OFFGRAM_CONFIG"]).expanduser())
    paths += [Path.home() / ".config" / "offgram" / "config.py",
              Path(__file__).resolve().parent / "config.py",
              Path.cwd() / "config.py"]
    for p in paths:
        if p.is_file():
            spec = importlib.util.spec_from_file_location("offgram_user_config", p)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            collection = collection or str(getattr(mod, "COLLECTION", "") or "")
            login = login or str(getattr(mod, "INSTALOADER_LOGIN", "") or "")
            break
    return collection, login


_collection, INSTALOADER_LOGIN = _load_config()
if not _collection:
    raise SystemExit(
        "offgram: no collection configured. Set $OFFGRAM_COLLECTION, or create "
        "~/.config/offgram/config.py (copy config.example.py) with COLLECTION set.")
COLLECTION = Path(_collection).expanduser()
ROOT = COLLECTION                          # the archive root
DB_PATH = ROOT / ".stogram.sqlite"         # optional legacy 4K Stogram db (captions/urls)
PORT = int(os.environ.get("OFFGRAM_PORT", "8077"))
HOST = "127.0.0.1"

# Cache lives on LOCAL disk, never inside the archive.
CACHE_ROOT = Path.home() / ".cache" / "offgram"
INDEX_FILE = CACHE_ROOT / "index.json"
THUMB_DIR = CACHE_ROOT / "thumbs"                # generated grid thumbnails (images + video)
THUMB_PX = 360                                   # thumbnail square size, px
SCAN_WORKERS = 12                                # parallel profile scans (I/O-latency bound)
PREWARM_ON = os.environ.get("OFFGRAM_PREWARM", "1") != "0"   # background thumbnail pre-warm
PREWARM_WORKERS = 2                              # gentle: leaves thumb slots for live browsing
STAMPS_FILE = CACHE_ROOT / "latest-stamps.ini"   # instaloader incremental-update stamps

SECTIONS = ["posts", "story", "reels", "highlights", "tagged"]

# instaloader is run as a subprocess for the update buttons. offgram REQUIRES the
# forked/patched instaloader (see requirements.txt) — stock 4.15.1 is broken
# against current Instagram (retired doc_id / GraphQL changes). The default below
# runs `python -m instaloader` in offgram's own interpreter, so installing
# requirements.txt into that env wires up the fork automatically:
#   instaloader @ git+https://github.com/mholzinger/instaloader@fix-profile-metadata-web-profile-info
# Login is required (Instagram 403s anonymous requests). INSTALOADER_LOGIN (from
# config.py) names a session in ~/.config/instaloader/ (make one via `instaloader
# --login USER`).
INSTALOADER_CMD = [sys.executable, "-m", "instaloader"]
INSTALOADER_EXTRA = []                              # extra flags, posts pass only
# Common flags for every instaloader pass (--dirname-pattern + --latest-stamps are
# added per-pass; no --quiet, so progress streams into the in-app log panel).
INSTALOADER_COMMON = ["--fast-update", "--no-video-thumbnails"]
# Ephemeral / secondary content: each runs as its own pass routed into the matching
# section subfolder so offgram's tabs pick it up. OFFGRAM_EPHEMERAL=0 -> posts only.
# (Reels come down with posts — Instagram now serves them in the main feed.)
GRAB_EPHEMERAL = os.environ.get("OFFGRAM_EPHEMERAL", "1") != "0"
PASS_DELAY = float(os.environ.get("OFFGRAM_PASS_DELAY", "6"))   # gap between passes
# Each pass: (label, dirname-pattern, flags). Highlights MUST use {profile} not
# {target}: instaloader sets {target}=<profile>/<highlight-title> for highlights,
# which would scatter them into per-collection folders offgram can't see. {profile}
# is always the account, so all highlights land flat in <profile>/highlights/.
# (tagged is omitted: instaloader gives it a ":tagged" target that collides.)
EPHEMERAL_PASSES = [("story", "{target}/story", ["--no-posts", "--stories"]),
                    ("highlights", "{profile}/highlights", ["--no-posts", "--highlights"]),
                    ("reels", "{target}/reels", ["--no-posts", "--reels"])]

IMAGE_EXT = {".jpg", ".jpeg", ".png", ".webp", ".gif"}
VIDEO_EXT = {".mp4", ".mov", ".webm", ".mkv"}
MEDIA_EXT = IMAGE_EXT | VIDEO_EXT

ID_RE = re.compile(r"(\d{6,}_\d{4,})")
DATE_RE = re.compile(r"(\d{4})-(\d{2})-(\d{2})[ _](\d{2})[.\-](\d{2})[.\-](\d{2})")

# ---------------------------------------------------------------------------
# Old 4K Stogram database -> in-memory caption / url index (read once)
# ---------------------------------------------------------------------------
CAPTIONS = {}                                       # instagram_id -> {caption,url,ts}


def local_db_copy():
    """Copy the legacy 4K Stogram sqlite to local disk (a bulk copy beats
    SQLite's random page reads when the archive is on a network share).
    Re-copies only when size/mtime changed."""
    import shutil
    if not DB_PATH.exists():
        return None
    CACHE_ROOT.mkdir(parents=True, exist_ok=True)
    local = CACHE_ROOT / "stogram.sqlite"
    try:
        src = DB_PATH.stat()
        if (not local.exists() or local.stat().st_size != src.st_size
                or local.stat().st_mtime < src.st_mtime):
            print("copying %s (%.0f MB) to local cache…"
                  % (DB_PATH.name, src.st_size / 1e6))
            shutil.copy2(DB_PATH, local)
        return local
    except Exception as exc:                          # noqa: BLE001
        print("warning: could not copy db locally (%s); reading it in place" % exc)
        return DB_PATH


def load_db_index():
    src = local_db_copy()
    if src is None:
        print("note: %s not found — old-file captions will be blank" % DB_PATH.name)
        return
    try:
        uri = "file:%s?mode=ro&immutable=1" % urllib.parse.quote(str(src))
        con = sqlite3.connect(uri, uri=True)
        for iid, title, web_url, ctime in con.execute(
                "SELECT instagram_id, title, web_url, created_time FROM photos"):
            if iid:
                CAPTIONS[iid] = {"caption": title or "", "url": web_url or "",
                                 "ts": ctime or 0}
        con.close()
        print("loaded %d captions from %s" % (len(CAPTIONS), DB_PATH.name))
    except Exception as exc:                         # noqa: BLE001
        print("warning: could not read %s (%s)" % (DB_PATH.name, exc))


# ---------------------------------------------------------------------------
# Index: the cached map of the whole collection (built once by scanning the archive)
# ---------------------------------------------------------------------------
# INDEX = {"built": ts, "profiles": {name: {counts, total, cover, mtime,
#           sections: {sec: [[filename, has_sidecar], ...]}}}}
INDEX = {"built": 0, "profiles": {}}
INDEX_LOCK = threading.Lock()
SCAN = {"running": False, "done": 0, "total": 0, "current": ""}


def is_hidden(name):
    return name.startswith(".")


def list_profile_names():
    out = []
    try:
        with os.scandir(ROOT) as it:
            for e in it:
                if e.is_dir() and not is_hidden(e.name):
                    out.append(e.name)
    except FileNotFoundError:
        pass
    out.sort(key=str.lower)
    return out


def section_dir(profile, section):
    return ROOT / profile if section == "posts" else ROOT / profile / section


def scan_profile(profile):
    """One deep read of a profile from the archive. Returns its index record."""
    rec = {"counts": {}, "total": 0, "cover": None, "sections": {}, "mtime": 0}
    try:
        rec["mtime"] = (ROOT / profile).stat().st_mtime
    except OSError:
        pass
    # legacy profiles already have 4K Stogram thumbnails; the pre-warm skips them.
    rec["legacy"] = (ROOT / profile / ".thumb.stogram").is_dir()
    cover_key = ""
    for section in SECTIONS:
        d = section_dir(profile, section)
        media, meta_stems = [], set()
        if d.is_dir():
            with os.scandir(d) as it:
                for e in it:
                    if not e.is_file() or is_hidden(e.name):
                        continue
                    low = e.name.lower()
                    if low.endswith(".json.xz"):
                        meta_stems.add(e.name[:-8])      # instaloader metadata sidecar
                    elif low.endswith(".txt"):
                        meta_stems.add(Path(e.name).stem)
                    elif Path(e.name).suffix.lower() in MEDIA_EXT:
                        media.append(e.name)
        # a media file has caption metadata if a .txt/.json.xz sidecar matches its
        # stem or the post's base stem (carousel children share one sidecar).
        entries = []
        for n in media:
            stem = Path(n).stem
            base = re.sub(r"_\d+$", "", stem)
            entries.append([n, (stem in meta_stems or base in meta_stems)])
        rec["sections"][section] = entries
        rec["counts"][section] = len(entries)
        rec["total"] += len(entries)
        if section == "posts":
            for n in media:
                if Path(n).suffix.lower() in IMAGE_EXT and n > cover_key:
                    cover_key, rec["cover"] = n, n
    if rec["cover"] is None:                          # fall back to any image
        for section in SECTIONS:
            for n, _ in rec["sections"][section]:
                if Path(n).suffix.lower() in IMAGE_EXT:
                    rec["cover"] = "%s/%s" % (section, n) if section != "posts" else n
                    break
            if rec["cover"]:
                break
    return rec


def save_index():
    try:
        CACHE_ROOT.mkdir(parents=True, exist_ok=True)
        tmp = INDEX_FILE.with_suffix(".tmp")
        with INDEX_LOCK:
            tmp.write_text(json.dumps(INDEX), encoding="utf-8")
        tmp.replace(INDEX_FILE)
    except Exception as exc:                          # noqa: BLE001
        print("warning: could not save index (%s)" % exc)


def load_index():
    global INDEX
    if INDEX_FILE.exists():
        try:
            INDEX = json.loads(INDEX_FILE.read_text(encoding="utf-8"))
            print("loaded cached index: %d profiles (built %s)"
                  % (len(INDEX["profiles"]),
                     time.strftime("%Y-%m-%d %H:%M",
                                   time.localtime(INDEX["built"]))))
            return True
        except Exception as exc:                      # noqa: BLE001
            print("warning: bad index cache (%s) — will rebuild" % exc)
    return False


def rescan(profiles=None, full=False):
    """Background-safe scan. profiles=None means all."""
    if SCAN["running"]:
        return
    SCAN["running"] = True
    try:
        names = profiles if profiles is not None else list_profile_names()
        SCAN["total"], SCAN["done"] = len(names), 0
        # Scan profiles in parallel: the cost is per-directory I/O latency (worst
        # over a network share), which overlaps cleanly. Workers only read the
        # filesystem; INDEX writes stay on this thread under the lock.
        with ThreadPoolExecutor(max_workers=SCAN_WORKERS) as ex:
            futs = {ex.submit(scan_profile, n): n for n in names}
            for fut in as_completed(futs):
                name = futs[fut]
                SCAN["current"] = name
                try:
                    rec = fut.result()
                except Exception as exc:              # noqa: BLE001
                    print("scan error %s: %s" % (name, exc))
                    rec = None
                if rec is not None:
                    with INDEX_LOCK:
                        INDEX["profiles"][name] = rec
                SCAN["done"] += 1
                if SCAN["done"] % 10 == 0:
                    save_index()
        # drop profiles whose folders disappeared (only on a full scan)
        if profiles is None:
            live = set(names)
            with INDEX_LOCK:
                for gone in [p for p in INDEX["profiles"] if p not in live]:
                    del INDEX["profiles"][gone]
        INDEX["built"] = int(time.time())
        save_index()
        print("scan complete: %d profiles" % len(INDEX["profiles"]))
        start_prewarm()
    finally:
        SCAN["running"] = False
        SCAN["current"] = ""


# ---------------------------------------------------------------------------
# Background thumbnail pre-warm — generate cached thumbnails for instaloader
# profiles ahead of time so first-browse is instant. Legacy (4K Stogram) profiles
# already have thumbnails and are skipped; already-cached thumbs are a fast,
# local, no-network check.
# ---------------------------------------------------------------------------
PREWARM = {"running": False, "done": 0, "total": 0}


def prewarm_thumbs():
    if PREWARM["running"]:
        return
    PREWARM["running"] = True
    try:
        rels = []
        with INDEX_LOCK:
            for name, rec in INDEX["profiles"].items():
                # only profiles confirmed (by a current-format scan) to lack legacy
                # thumbnails; missing/unknown -> skip, so an old cache can't trigger
                # a full re-thumbnail of legacy content before a rescan.
                if rec.get("legacy") is not False:
                    continue
                for section, entries in rec.get("sections", {}).items():
                    for fn, _ in entries:
                        r = fn if section == "posts" else "%s/%s" % (section, fn)
                        rels.append("%s/%s" % (name, r))
        PREWARM["total"], PREWARM["done"] = len(rels), 0
        if not rels:
            return
        print("thumbnail pre-warm: %d media…" % len(rels))

        def one(rel):
            try:
                full = safe_under_root(rel)
                if full:
                    cached_thumb(full)
            except Exception:                         # noqa: BLE001
                pass
            PREWARM["done"] += 1

        with ThreadPoolExecutor(max_workers=PREWARM_WORKERS) as ex:
            list(ex.map(one, rels))
        print("thumbnail pre-warm complete")
    finally:
        PREWARM["running"] = False


def start_prewarm():
    if PREWARM_ON:
        threading.Thread(target=prewarm_thumbs, daemon=True).start()


# ---------------------------------------------------------------------------
# Heartbeat — ask Instagram (via the logged-in instaloader session) whether each
# profile is alive / private / gone / renamed. Makes live API calls under your
# account, so it is THROTTLED and runs on demand only, never automatically.
# ---------------------------------------------------------------------------
HEARTBEAT_FILE = CACHE_ROOT / "heartbeat.json"
HEARTBEAT = {"running": False, "done": 0, "total": 0, "current": ""}
HEALTH = {}                  # name -> {status, checked, userid, new_username, note}
HEARTBEAT_INTERVAL = float(os.environ.get("OFFGRAM_HEARTBEAT_INTERVAL", "4"))
_il = {"ctx": None, "tried": False}

# Active account — which instaloader session updates and heartbeat use. Defaults
# to the configured login; switchable at runtime among the saved sessions.
ACCOUNT_FILE = CACHE_ROOT / "account.txt"
ACTIVE_LOGIN = None


def list_sessions():
    d = Path.home() / ".config" / "instaloader"
    out = []
    if d.is_dir():
        for f in d.iterdir():
            if f.name.startswith("session-") and f.is_file():
                out.append(f.name[len("session-"):])
    return sorted(out)


def current_login():
    global ACTIVE_LOGIN
    if ACTIVE_LOGIN is None:
        try:
            if ACCOUNT_FILE.exists():
                ACTIVE_LOGIN = ACCOUNT_FILE.read_text(encoding="utf-8").strip()
        except Exception:                             # noqa: BLE001
            pass
        if not ACTIVE_LOGIN:
            ACTIVE_LOGIN = INSTALOADER_LOGIN
    return ACTIVE_LOGIN


def set_login(name):
    global ACTIVE_LOGIN
    name = (name or "").strip()
    if name not in list_sessions():
        return False
    ACTIVE_LOGIN = name
    try:
        CACHE_ROOT.mkdir(parents=True, exist_ok=True)
        ACCOUNT_FILE.write_text(name, encoding="utf-8")
    except Exception:                                 # noqa: BLE001
        pass
    _il["ctx"], _il["tried"] = None, False            # rebuild context as new account
    return True


def load_health():
    global HEALTH
    if HEARTBEAT_FILE.exists():
        try:
            HEALTH = json.loads(HEARTBEAT_FILE.read_text(encoding="utf-8"))
        except Exception:                             # noqa: BLE001
            HEALTH = {}


def save_health():
    try:
        CACHE_ROOT.mkdir(parents=True, exist_ok=True)
        HEARTBEAT_FILE.write_text(json.dumps(HEALTH), encoding="utf-8")
    except Exception:                                 # noqa: BLE001
        pass


def _il_context():
    """Lazily build a logged-in instaloader context, or None if unavailable.
    Imported lazily so the viewer still runs without instaloader installed."""
    if _il["tried"]:
        return _il["ctx"]
    _il["tried"] = True
    try:
        import instaloader
        loader = instaloader.Instaloader(quiet=True)
        if current_login():
            loader.load_session_from_file(current_login())
        _il["ctx"] = loader
    except Exception as exc:                          # noqa: BLE001
        print("heartbeat: instaloader/session unavailable (%s)" % exc)
        _il["ctx"] = None
    return _il["ctx"]


def profile_userid(name):
    """Instagram numeric user-id for a profile, parsed from the mediaid_ownerid
    token 4K Stogram embeds in filenames. Stable across username changes."""
    rec = INDEX["profiles"].get(name, {})
    for section, entries in rec.get("sections", {}).items():
        for fn, _ in entries:
            m = ID_RE.search(fn)
            if m:
                return m.group(1).rsplit("_", 1)[1]
    return None


def check_one(name):
    loader = _il_context()
    now = int(time.time())
    if loader is None:
        return {"status": "no-session", "checked": now}
    import instaloader
    try:
        p = instaloader.Profile.from_username(loader.context, name)
        return {"status": "private" if p.is_private else "alive",
                "checked": now, "userid": str(p.userid)}
    except instaloader.ProfileNotExistsException:
        uid = profile_userid(name)
        if uid:
            try:
                p = instaloader.Profile.from_id(loader.context, int(uid))
                if p.username.lower() != name.lower():
                    return {"status": "renamed", "checked": now,
                            "userid": str(p.userid), "new_username": p.username}
                return {"status": "private" if p.is_private else "alive",
                        "checked": now, "userid": str(p.userid)}
            except Exception:                         # noqa: BLE001
                return {"status": "dead", "checked": now}
        return {"status": "dead", "checked": now}
    except Exception as exc:                          # noqa: BLE001
        return {"status": "error", "checked": now, "note": str(exc)[:140]}


def heartbeat_all(profiles=None):
    if HEARTBEAT["running"]:
        return
    HEARTBEAT["running"] = True
    try:
        names = profiles if profiles is not None else list(INDEX["profiles"].keys())
        names = sorted(names, key=str.lower)
        HEARTBEAT["total"], HEARTBEAT["done"] = len(names), 0
        for i, name in enumerate(names):
            HEARTBEAT["current"] = name
            res = check_one(name)
            HEALTH[name] = res
            HEARTBEAT["done"] += 1
            if HEARTBEAT["done"] % 5 == 0:
                save_health()
            if res.get("status") == "no-session":
                break                                 # nothing will succeed; stop early
            if i < len(names) - 1:
                time.sleep(HEARTBEAT_INTERVAL)         # throttle: protect the account
        save_health()
        print("heartbeat complete")
    finally:
        HEARTBEAT["running"] = False
        HEARTBEAT["current"] = ""


def start_heartbeat(profiles=None):
    threading.Thread(target=heartbeat_all, kwargs={"profiles": profiles},
                     daemon=True).start()


def start_scan_thread(profiles=None):
    threading.Thread(target=rescan, kwargs={"profiles": profiles},
                     daemon=True).start()


# ---------------------------------------------------------------------------
# Building view items from the cached index (no archive access here)
# ---------------------------------------------------------------------------
def parse_meta(filename):
    m = ID_RE.search(filename)
    iid = m.group(1) if m else None
    info = CAPTIONS.get(iid) if iid else None
    if info and info["ts"]:
        return iid, info["ts"]
    d = DATE_RE.search(filename)
    if d:
        try:
            return iid, int(time.mktime(time.struct_time(
                (int(d.group(1)), int(d.group(2)), int(d.group(3)),
                 int(d.group(4)), int(d.group(5)), int(d.group(6)), 0, 0, -1))))
        except Exception:                             # noqa: BLE001
            pass
    return iid, 0


def profile_items(profile):
    rec = INDEX["profiles"].get(profile)
    if not rec:
        return []
    items = []
    for section in SECTIONS:
        for name, has_sc in rec["sections"].get(section, []):
            rel = name if section == "posts" else "%s/%s" % (section, name)
            rel = "%s/%s" % (profile, rel)
            iid, ts = parse_meta(name)
            info = CAPTIONS.get(iid) if iid else None
            items.append({
                "rel": rel,
                "section": section,
                "kind": "video" if Path(name).suffix.lower() in VIDEO_EXT else "image",
                "caption": (info["caption"] if info else ""),
                "url": (info["url"] if info else ""),
                "ts": ts,
                "sc": 1 if has_sc else 0,
            })
    items.sort(key=lambda x: (x["ts"], x["rel"]), reverse=True)
    return items


# ---------------------------------------------------------------------------
# Paths / thumbnails / posters (lazy archive access, one item at a time)
# ---------------------------------------------------------------------------
def safe_under_root(p):
    try:
        rp = (ROOT / p).resolve()
        rp.relative_to(ROOT)
        return rp
    except Exception:                                 # noqa: BLE001
        return None


def thumb_for(rel):
    full = safe_under_root(rel)
    if not full or not full.exists():
        return None
    # 1. reuse a legacy 4K Stogram thumbnail if present (already tiny, free)
    tdir = full.parent / ".thumb.stogram"
    for cand in (tdir / full.name, tdir / (full.stem + ".jpg")):
        if cand.exists():
            return cand
    # 2. a generated, cached thumbnail — for images AND videos. This is the win:
    #    instaloader images have no .thumb.stogram, so the grid used to serve the
    #    full original (hundreds of KB per tile); a thumb is ~10-15 KB.
    t = cached_thumb(full)
    if t:
        return t
    # 3. no ffmpeg available: fall back to the original image (videos get none)
    return full if full.suffix.lower() in IMAGE_EXT else None


# cap concurrent ffmpeg thumbnailers so fast scrolling can't fork a swarm
_thumb_sem = threading.Semaphore(4)


def cached_thumb(full):
    """A small square JPEG thumbnail for an image or video, generated once with
    ffmpeg and cached locally. Returns the cache path, or None if ffmpeg fails."""
    try:
        THUMB_DIR.mkdir(parents=True, exist_ok=True)
        key = re.sub(r"[^A-Za-z0-9_.-]", "_",
                     str(full.relative_to(ROOT)).replace(os.sep, "__"))
    except Exception:                                 # noqa: BLE001
        return None
    out = THUMB_DIR / (key + ".jpg")
    if out.exists():
        return out
    with _thumb_sem:
        if out.exists():
            return out
        vf = ("scale=%d:%d:force_original_aspect_ratio=increase,crop=%d:%d"
              % (THUMB_PX, THUMB_PX, THUMB_PX, THUMB_PX))
        cmd = ["ffmpeg", "-nostdin"]
        if full.suffix.lower() in VIDEO_EXT:
            cmd += ["-ss", "1"]                        # grab a frame ~1s in
        cmd += ["-i", str(full), "-frames:v", "1", "-vf", vf, "-q:v", "5"]
        fd, tmp = tempfile.mkstemp(dir=str(THUMB_DIR), suffix=".jpg")
        os.close(fd)
        cmd += ["-y", tmp]
        try:
            subprocess.run(cmd, stdout=subprocess.DEVNULL,
                           stderr=subprocess.DEVNULL, timeout=40)
            if os.path.getsize(tmp) > 0:
                os.replace(tmp, out)
        except Exception:                             # noqa: BLE001
            pass
        finally:
            if os.path.exists(tmp):
                os.remove(tmp)
    return out if out.exists() else None


def _caption_from_node(node):
    c = node.get("caption")
    if isinstance(c, str) and c.strip():
        return c.strip()
    try:
        return node["edge_media_to_caption"]["edges"][0]["node"]["text"].strip()
    except Exception:                                 # noqa: BLE001
        pass
    cap = (node.get("iphone_struct") or {}).get("caption")
    if isinstance(cap, dict):
        return (cap.get("text") or "").strip()
    if isinstance(cap, str):
        return cap.strip()
    return ""


def read_post_meta(rel):
    """Lazily read caption + original-post URL from instaloader sidecars next to
    the media at rel: the '.json.xz' metadata (caption + shortcode->URL), falling
    back to a '.txt' caption. Carousel children share the post's base sidecar."""
    full = safe_under_root(rel)
    if not full:
        return "", ""
    d, stem = full.parent, full.stem
    base = re.sub(r"_\d+$", "", stem)
    cap, url = "", ""
    for s in (stem, base):
        jx = d / (s + ".json.xz")
        if jx.exists():
            try:
                node = json.loads(lzma.open(jx).read()).get("node", {})
                sc = node.get("shortcode") or (node.get("iphone_struct") or {}).get("code")
                if sc:
                    url = "https://www.instagram.com/p/%s/" % sc
                cap = _caption_from_node(node)
            except Exception:                         # noqa: BLE001
                pass
            break
    if not cap:
        for s in (stem, base):
            t = d / (s + ".txt")
            if t.exists():
                try:
                    cap = t.read_text(encoding="utf-8", errors="replace").strip()
                except Exception:                     # noqa: BLE001
                    pass
                break
    return cap, url


# ---------------------------------------------------------------------------
# instaloader update jobs
# ---------------------------------------------------------------------------
JOBS = {}
JOBS_LOCK = threading.Lock()


# instaloader incremental-update support. Without latest-stamps, --fast-update
# can't recognize 4K Stogram's differently-named files and re-downloads a
# profile's entire history. Seeding the stamp from what offgram already has makes
# even the first update incremental.
STAMP_KEYS = {"posts": "post-timestamp", "story": "story-timestamp",
              "reels": "reels-timestamp", "tagged": "tagged-timestamp"}
STAMP_ISO = "%Y-%m-%dT%H:%M:%S.%f%z"


def seed_stamps(profile):
    """Before a profile's FIRST update, seed latest-stamps from the newest item
    already indexed, so instaloader fetches only newer content rather than
    re-downloading everything already archived (under any naming)."""
    rec = INDEX["profiles"].get(profile)
    if not rec:
        return
    cfg = configparser.ConfigParser()
    if STAMPS_FILE.exists():
        cfg.read(STAMPS_FILE)
    if cfg.has_section(profile):
        return                      # already tracked by a real update; never override
    newest = {}
    for section, key in STAMP_KEYS.items():
        best = 0
        for name, _ in rec["sections"].get(section, []):
            _, ts = parse_meta(name)
            best = max(best, ts)
        if best:
            newest[key] = best
    if not newest:
        return
    cfg.add_section(profile)
    for key, ts in newest.items():
        cfg.set(profile, key,
                datetime.fromtimestamp(ts, timezone.utc).strftime(STAMP_ISO))
    CACHE_ROOT.mkdir(parents=True, exist_ok=True)
    with open(STAMPS_FILE, "w") as f:
        cfg.write(f)
    JOBS[profile]["log"].append(
        "offgram: seeded latest-stamps from existing archive (%s)"
        % ", ".join("%s=%s" % (k, datetime.fromtimestamp(v, timezone.utc).date())
                    for k, v in newest.items()))


def run_update(profiles):
    for profile in profiles:
        with JOBS_LOCK:
            JOBS[profile] = {"running": True, "log": [], "rc": None}
    for profile in profiles:
        seed_stamps(profile)
        _run_one(profile)
        # refresh just this profile in the index after download
        try:
            rec = scan_profile(profile)
            with INDEX_LOCK:
                INDEX["profiles"][profile] = rec
            save_index()
        except Exception:                             # noqa: BLE001
            pass


def _il_run(profile, dirpat, flags, extra=None):
    """Run one instaloader pass, streaming its output into the profile's job log."""
    cmd = list(INSTALOADER_CMD) + INSTALOADER_COMMON
    cmd += ["--dirname-pattern=" + dirpat, "--latest-stamps", str(STAMPS_FILE)]
    cmd += list(flags) + list(extra or [])
    if current_login():
        cmd += ["--login", current_login()]
    cmd += [profile]
    log = JOBS[profile]["log"]
    log.append("$ " + " ".join(cmd))
    try:
        proc = subprocess.Popen(
            cmd, cwd=str(ROOT), stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)
        for line in proc.stdout:
            line = line.rstrip("\n")
            if line:
                log.append(line)
                if len(log) > 500:
                    del log[:len(log) - 500]
        proc.wait()
        return proc.returncode
    except Exception as exc:                          # noqa: BLE001
        log.append("error: %s" % exc)
        return -1


def _run_one(profile):
    log = JOBS[profile]["log"]
    rc = _il_run(profile, "{target}", [], INSTALOADER_EXTRA)     # posts (+ reels, pic)
    if GRAB_EPHEMERAL:
        for sub, dirpat, flags in EPHEMERAL_PASSES:
            time.sleep(PASS_DELAY)                     # space out passes to avoid throttling
            log.append("--- fetching %s ---" % sub)
            _il_run(profile, dirpat, flags)
    with JOBS_LOCK:
        JOBS[profile]["running"] = False
        JOBS[profile]["rc"] = rc
    log.append("--- finished (exit %s) ---" % rc)


def any_running():
    with JOBS_LOCK:
        return any(j["running"] for j in JOBS.values())


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------
CSS = """
*{box-sizing:border-box}
body{margin:0;background:#0e0e10;color:#e7e7ea;
 font:15px/1.4 -apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}
a{color:#7db4ff;text-decoration:none}
header{position:sticky;top:0;z-index:10;background:#16161a;
 border-bottom:1px solid #26262c;padding:12px 18px;display:flex;
 align-items:center;gap:10px;flex-wrap:wrap}
header h1{font-size:17px;margin:0;font-weight:600}
#search{background:#0e0e10;border:1px solid #3a3a44;color:#e7e7ea;padding:6px 10px;
 border-radius:7px;font-size:13px;width:210px}
#search:focus{outline:none;border-color:#2c5fb3}
#acct{background:#0e0e10;border:1px solid #3a3a44;color:#e7e7ea;padding:5px 8px;
 border-radius:7px;font-size:13px}
.legend{position:sticky;top:53px;z-index:9;display:flex;flex-wrap:wrap;gap:16px;
 align-items:center;padding:7px 18px;color:#9a9aa3;font-size:12px;
 background:#121216;border-bottom:1px solid #1c1c22}
.legend span.dot{margin-right:5px}
.addbar{margin:0 0 14px;padding:10px 14px;background:#16161a;border:1px solid #2a2a32;
 border-radius:8px;display:none}
.sp{flex:1}.sub{color:#9a9aa3;font-size:13px}
.btn{background:#2a2a32;border:1px solid #3a3a44;color:#e7e7ea;padding:6px 12px;
 border-radius:7px;cursor:pointer;font-size:13px}
.btn:hover{background:#34343e}
.btn.go{background:#2c5fb3;border-color:#2c5fb3}.btn.go:hover{background:#3570cf}
.wrap{padding:18px}
.grid{display:grid;gap:12px;grid-template-columns:repeat(auto-fill,minmax(190px,1fr))}
.card{background:#16161a;border:1px solid #24242a;border-radius:10px;overflow:hidden}
.card a.thumb{display:block;aspect-ratio:1/1;background:#000;position:relative}
.card img{width:100%;height:100%;object-fit:cover;display:block}
.card .meta{padding:8px 10px}.card .meta b{font-weight:600}
.card .s2{color:#9a9aa3;font-size:12px;margin-top:2px}
.dot{display:inline-block;width:9px;height:9px;border-radius:50%;margin-right:6px;
 vertical-align:middle;flex:none}
.badge{position:absolute;top:6px;right:6px;background:rgba(0,0,0,.65);
 padding:2px 7px;border-radius:20px;font-size:11px}
.play{position:absolute;inset:0;display:flex;align-items:center;justify-content:center;
 font-size:34px;color:#fff;text-shadow:0 1px 6px #000;pointer-events:none}
.tabs{display:flex;gap:8px;flex-wrap:wrap;margin:4px 0 16px}
.tab{padding:5px 12px;border-radius:20px;background:#16161a;border:1px solid #2a2a32;
 cursor:pointer;font-size:13px}
.tab.active{background:#2c5fb3;border-color:#2c5fb3}
.mediagrid{display:grid;gap:6px;grid-template-columns:repeat(auto-fill,minmax(150px,1fr))}
.cell{aspect-ratio:1/1;background:#000;position:relative;cursor:pointer;
 border-radius:6px;overflow:hidden}
.cell img{width:100%;height:100%;object-fit:cover}
.banner{background:#23314a;border:1px solid #2c5fb3;border-radius:8px;
 padding:10px 14px;margin:0 0 16px}
#log{position:fixed;right:0;bottom:0;width:min(540px,100%);max-height:48vh;
 min-height:96px;overflow:auto;background:#0a0a0c;border:1px solid #2a2a32;
 border-radius:10px 0 0 0;padding:10px 12px;
 font:12px/1.45 ui-monospace,Menlo,monospace;white-space:pre-wrap;
 display:none;z-index:60}
.loghdr{font-family:-apple-system,sans-serif;color:#9a9aa3;margin:-2px 0 6px;
 border-bottom:1px solid #1c1c22;padding-bottom:4px}
#log .x{float:right;cursor:pointer;color:#9a9aa3}
#lb{position:fixed;inset:0;background:rgba(0,0,0,.93);display:none;z-index:50;
 flex-direction:column}
#lb .stage{flex:1;min-height:0;width:100%;display:flex;
 align-items:center;justify-content:center}
#lb .stage img,#lb .stage video{max-width:96vw;max-height:100%;display:block}
#lb .cap{flex:none;width:100%;max-height:24vh;overflow:auto;box-sizing:border-box;
 padding:10px 18px;background:rgba(0,0,0,.55);white-space:pre-wrap}
#lb .nav{position:fixed;top:50%;font-size:40px;color:#fff;cursor:pointer;
 padding:0 18px;user-select:none;transform:translateY(-50%)}
#lb .nav.l{left:0}#lb .nav.r{right:0}
#lb .close{position:fixed;top:14px;right:20px;font-size:30px;cursor:pointer}
"""

JS_COMMON = """
let ITEMS=[],cur=0;
function openLB(i){cur=i;renderLB();document.getElementById('lb').style.display='flex';}
function closeLB(){document.getElementById('lb').style.display='none';
 let s=document.querySelector('#lb .stage');if(s)s.innerHTML='';}
function step(d){cur=(cur+d+ITEMS.length)%ITEMS.length;renderLB();}
function escapeHTML(s){return s.replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));}
function renderLB(){let it=ITEMS[cur];let s=document.querySelector('#lb .stage');
 let m='/media?p='+encodeURIComponent(it.rel);
 s.innerHTML=it.kind==='video'
  ?'<video src="'+m+'" controls autoplay playsinline></video>'
  :'<img src="'+m+'">';
 let when=it.ts?new Date(it.ts*1000).toLocaleString():'';
 let link=it.url?' &nbsp;·&nbsp; <a href="'+it.url+'" target="_blank">open original ↗</a>':'';
 let cap=document.getElementById('cap');
 cap.innerHTML='<b>'+it.section+'</b> &nbsp; '+when+link+'<br>'+
  (it.caption?escapeHTML(it.caption):(it.sc?'<i>loading caption…</i>':'<i>no caption</i>'));
 if(!it.caption&&it.sc){it.sc=0;fetch('/caption?p='+encodeURIComponent(it.rel))
  .then(r=>r.json()).then(d=>{if(d.caption)it.caption=d.caption;if(d.url)it.url=d.url;
   if(ITEMS[cur]===it)renderLB();});}}
document.addEventListener('keydown',e=>{
 if(document.getElementById('lb').style.display!=='flex')return;
 if(e.key==='Escape')closeLB();if(e.key==='ArrowLeft')step(-1);if(e.key==='ArrowRight')step(1);});
function showLog(){document.getElementById('log').style.display='block';}
function renderLog(j){var lines=[],jobs=(j&&j.jobs)||{};
 for(var k in jobs){lines.push('### '+k+(jobs[k].running?' (running)':' (done)'));
  lines.push(jobs[k].log.slice(-20).join('\\n'));}
 document.getElementById('logbody').textContent=lines.length?lines.join('\\n')
  :'No activity yet.\\nRun an update (\\u21bb) and progress streams here live.';}
function poll(reloadWhenDone){fetch('/status').then(r=>r.json()).then(j=>{
 renderLog(j);
 if(j.any)setTimeout(()=>poll(reloadWhenDone),1500);
 else if(reloadWhenDone)setTimeout(()=>location.reload(),1200);});}
function upd(p){showLog();fetch('/update',{method:'POST',
 headers:{'Content-Type':'application/x-www-form-urlencoded'},
 body:'profile='+encodeURIComponent(p)}).then(()=>poll(true));}
function updAll(){if(!confirm('Run instaloader for every profile? This can take a while for large collections.'))return;
 showLog();fetch('/update-all',{method:'POST'}).then(()=>poll(true));}
function rescan(){fetch('/rescan',{method:'POST'}).then(()=>{location.reload();});}
function heartbeat(){if(!confirm('Ping Instagram for every profile to check alive/private/gone/renamed? Throttled, and it uses your login session.'))return;
 fetch('/heartbeat',{method:'POST'}).then(hbpoll);}
function hbpoll(){fetch('/status').then(r=>r.json()).then(j=>{var h=j.heartbeat;
 var el=document.getElementById('hbstat');
 if(h&&h.running){if(el)el.textContent=' · checking '+h.done+'/'+h.total+' '+(h.current||'');
  setTimeout(hbpoll,1500);}else{location.reload();}});}
function toggleLog(){var l=document.getElementById('log');
 if(l.style.display==='block'){l.style.display='none';return;}
 l.style.display='block';fetch('/status').then(function(r){return r.json();}).then(renderLog);}
function switchAcct(){var v=document.getElementById('acct').value;
 fetch('/account',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},
  body:'login='+encodeURIComponent(v)}).then(function(){location.reload();});}
function igName(s){return (s||'').toLowerCase().replace(/^@/,'').replace(/[^a-z0-9._]/g,'');}
function doSearch(){var q=igName(document.getElementById('search').value);
 var cards=document.querySelectorAll('.card'),any=false,exact=false;
 cards.forEach(function(c){var n=c.getAttribute('data-name')||'';
  var hit=q===''||n.indexOf(q)>=0;c.style.display=hit?'':'none';
  if(hit)any=true;if(n===q)exact=true;});
 var ab=document.getElementById('addbar');ab.textContent='';
 if(q&&!exact){ab.style.display='block';
  var sp=document.createElement('span');sp.innerHTML='Not archived yet: <b>@'+q+'</b> &nbsp; ';
  var b=document.createElement('button');b.className='btn go';b.textContent='+ Archive @'+q;
  b.onclick=function(){addProfile(q);};
  ab.appendChild(sp);ab.appendChild(b);
  if(!any){var s=document.createElement('span');s.className='sub';
   s.textContent='  (no existing matches)';ab.appendChild(s);}}
 else{ab.style.display='none';}}
function addSearched(){var q=igName(document.getElementById('search').value);if(q)addProfile(q);}
function addProfile(name){name=igName(name);if(!name)return;
 if(!confirm('Start archiving @'+name+' with instaloader? It will download the profile.'))return;
 showLog();fetch('/add',{method:'POST',
  headers:{'Content-Type':'application/x-www-form-urlencoded'},
  body:'profile='+encodeURIComponent(name)}).then(function(){poll(true);});}
"""


def page(title, body, extra_js=""):
    return ("<!doctype html><html><head><meta charset='utf-8'>"
            "<meta name='viewport' content='width=device-width,initial-scale=1'>"
            "<title>%s</title><style>%s</style></head><body>%s"
            "<div id='lb'><span class='close' onclick='closeLB()'>×</span>"
            "<span class='nav l' onclick='step(-1)'>‹</span>"
            "<span class='nav r' onclick='step(1)'>›</span>"
            "<div class='stage'></div><div class='cap' id='cap'></div></div>"
            "<div id='log'><div class='loghdr'>activity log"
            "<span class='x' onclick=\"document.getElementById('log')"
            ".style.display='none'\">×</span></div><div id='logbody'></div></div>"
            "<script>%s</script><script>%s</script></body></html>"
            % (html.escape(title), CSS, body, JS_COMMON, extra_js)).encode("utf-8")


def scan_banner():
    if SCAN["running"]:
        pct = int(100 * SCAN["done"] / SCAN["total"]) if SCAN["total"] else 0
        return ("<div class='banner'>Indexing the archive… %d/%d profiles (%d%%) — "
                "currently <b>%s</b>. This page auto-refreshes.</div>"
                % (SCAN["done"], SCAN["total"], pct, html.escape(SCAN["current"] or "")))
    return ""


HEALTH_COLOR = {"alive": "#3fb950", "private": "#d29922", "dead": "#f85149",
                "renamed": "#539bf5", "error": "#8b949e", "no-session": "#8b949e"}


def health_dot(h):
    if not h:
        return ("<span class='dot' style='background:transparent;"
                "box-shadow:inset 0 0 0 1.6px #6e7681' title='not checked'></span>")
    color = HEALTH_COLOR.get(h.get("status"), "#8b949e")
    title = h.get("status", "?")
    if h.get("new_username"):
        title += " → " + h["new_username"]
    if h.get("checked"):
        title += " · " + time.strftime("%Y-%m-%d", time.localtime(h["checked"]))
    return ("<span class='dot' style='background:%s' title='%s'></span>"
            % (color, html.escape(title)))


def render_index():
    with INDEX_LOCK:
        profiles = sorted(INDEX["profiles"].items(), key=lambda kv: kv[0].lower())
    auto = "<meta http-equiv='refresh' content='4'>" if SCAN["running"] else ""
    if not profiles and SCAN["running"]:
        body = ("<header><h1>offgram</h1><span class='sp'></span></header>"
                "<div class='wrap'>%s</div>" % scan_banner())
        return page("indexing…", body).replace("<head>", "<head>" + auto)
    cards = []
    for name, rec in profiles:
        pe = urllib.parse.quote(name)
        cover = rec.get("cover")
        if cover:
            crel = "%s/%s" % (name, cover)
            img = "<img loading='lazy' src='/thumb?p=%s'>" % urllib.parse.quote(crel)
        else:
            img = "<div class='play'>▦</div>"
        bits = ", ".join("%d %s" % (rec["counts"][k], k)
                         for k in SECTIONS if rec["counts"].get(k))
        cards.append(
            "<div class='card' data-name='%s'><a class='thumb' href='/p/%s'>%s"
            "<span class='badge'>%d</span></a><div class='meta'>"
            "<b>%s%s</b><div class='s2'>%s</div>"
            "<button class='btn' style='margin-top:8px' onclick=\"upd('%s')\">↻ update</button>"
            "</div></div>"
            % (html.escape(name.lower()), pe, img, rec["total"],
               health_dot(HEALTH.get(name)), html.escape(name),
               html.escape(bits or "empty"), pe))
    built = time.strftime("%Y-%m-%d %H:%M", time.localtime(INDEX.get("built", 0)))
    legend = ("<div class='legend'>"
              "<span><span class='dot' style='background:#3fb950'></span>alive</span>"
              "<span><span class='dot' style='background:#d29922'></span>private</span>"
              "<span><span class='dot' style='background:#f85149'></span>dead</span>"
              "<span><span class='dot' style='background:#539bf5'></span>renamed</span>"
              "<span><span class='dot' style='background:transparent;"
              "box-shadow:inset 0 0 0 1.6px #6e7681'></span>not checked</span>"
              "<span style='margin-left:auto;color:#6e7681'>hover a dot for details</span>"
              "</div>")
    sessions = list_sessions()
    cur = current_login()
    if sessions:
        opts = "".join("<option value='%s'%s>@%s</option>"
                       % (html.escape(s), " selected" if s == cur else "",
                          html.escape(s)) for s in sessions)
        acct = ("<select id='acct' title='active instaloader account' "
                "onchange='switchAcct()'>%s</select>" % opts)
    else:
        acct = "<span class='sub'>no login</span>"
    body = ("%s<header><h1>offgram</h1>"
            "<input id='search' placeholder='search, or type @name to add…' "
            "oninput='doSearch()' onkeydown='if(event.key===&quot;Enter&quot;)addSearched()'>"
            "<span class='sub'>%d profiles · indexed %s</span>"
            "<span class='sub' id='hbstat'></span><span class='sp'></span>"
            "<span class='sub'>as</span>%s"
            "<button class='btn' onclick='heartbeat()'>♥ Check all</button>"
            "<button class='btn' onclick='rescan()'>⟳ rescan</button>"
            "<button class='btn go' onclick='updAll()'>↻ Update all</button>"
            "<button class='btn' onclick='toggleLog()'>▤ log</button></header>"
            "%s<div class='wrap'><div class='addbar' id='addbar'></div>"
            "%s<div class='grid'>%s</div></div>"
            % (auto, len(profiles), built, acct, legend, scan_banner(),
               "".join(cards)))
    return page("offgram", body)


def render_profile(profile):
    if profile not in INDEX["profiles"]:
        return None
    items = profile_items(profile)
    data = [{"rel": it["rel"], "kind": it["kind"], "caption": it["caption"],
             "url": it["url"], "ts": it["ts"], "section": it["section"], "sc": it["sc"]}
            for it in items]
    secset = [s for s in SECTIONS if any(it["section"] == s for it in items)]
    tabs = ["<span class='tab active' data-sec='all' onclick='filt(this)'>all</span>"]
    tabs += ["<span class='tab' data-sec='%s' onclick='filt(this)'>%s</span>" % (s, s)
             for s in secset]
    pe = urllib.parse.quote(profile)
    body = ("<header><a href='/' class='btn'>‹ all</a><h1>%s</h1>"
            "<span class='sub'>%d items</span><span class='sp'></span>"
            "<button class='btn go' onclick=\"upd('%s')\">↻ update this profile</button></header>"
            "<div class='wrap'><div class='tabs'>%s</div>"
            "<div class='mediagrid' id='mg'></div>"
            "<div id='sentinel' style='height:1px'></div></div>"
            % (html.escape(profile), len(items), pe, "".join(tabs)))
    # Windowed grid: cells are rendered from ITEMS in batches as you scroll, so a
    # huge profile doesn't build thousands of DOM nodes (or a giant HTML page) up
    # front. openLB indexes the full ITEMS array, so the lightbox is unaffected.
    js = ("ITEMS=%s;\n"
          "var BATCH=150,shown=0,gfilter='all',_idxs=[];\n"
          "function cellHTML(it,i){var p=it.kind==='video'?\"<div class='play'>\\u25b6</div>\":'';\n"
          " return \"<div class='cell' data-sec='\"+it.section+\"' onclick='openLB(\"+i+\")'>\"+\n"
          "  \"<img loading='lazy' src='/thumb?p=\"+encodeURIComponent(it.rel)+\"'>\"+p+\"</div>\";}\n"
          "function _vis(){var o=[];for(var i=0;i<ITEMS.length;i++){"
          "if(gfilter==='all'||ITEMS[i].section===gfilter)o.push(i);}return o;}\n"
          "function renderMore(){var mg=document.getElementById('mg');"
          "var end=Math.min(shown+BATCH,_idxs.length),h='';"
          "for(var k=shown;k<end;k++){var i=_idxs[k];h+=cellHTML(ITEMS[i],i);}"
          "mg.insertAdjacentHTML('beforeend',h);shown=end;"
          "document.getElementById('sentinel').style.display=shown<_idxs.length?'':'none';}\n"
          "function resetGrid(){document.getElementById('mg').innerHTML='';shown=0;"
          "_idxs=_vis();renderMore();}\n"
          "function filt(el){document.querySelectorAll('.tab').forEach("
          "function(t){t.classList.remove('active');});el.classList.add('active');"
          "gfilter=el.dataset.sec;resetGrid();}\n"
          "new IntersectionObserver(function(es){es.forEach(function(e){"
          "if(e.isIntersecting)renderMore();});},{rootMargin:'1000px'})"
          ".observe(document.getElementById('sentinel'));\n"
          "resetGrid();"
          % json.dumps(data))
    return page(profile, body, js)


# ---------------------------------------------------------------------------
# HTTP server
# ---------------------------------------------------------------------------
class Handler(http.server.BaseHTTPRequestHandler):
    protocol_version = "HTTP/1.1"

    def log_message(self, *a):
        pass

    def handle(self):
        # browsers routinely drop thumbnail/video connections mid-flight;
        # don't dump a traceback for that.
        try:
            super().handle()
        except (ConnectionResetError, BrokenPipeError):
            pass

    def _send(self, code, body, ctype="text/html; charset=utf-8", extra=None):
        self.send_response(code)
        self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body)))
        for k, v in (extra or {}).items():
            self.send_header(k, v)
        self.end_headers()
        if self.command != "HEAD":
            self.wfile.write(body)

    def do_GET(self):
        u = urllib.parse.urlparse(self.path)
        path, qs = u.path, urllib.parse.parse_qs(u.query)
        if path == "/":
            return self._send(200, render_index())
        if path.startswith("/p/"):
            b = render_profile(urllib.parse.unquote(path[3:]))
            return self._send(200, b) if b else self._send(404, b"no such profile")
        if path == "/thumb":
            return self.serve_thumb(qs.get("p", [""])[0])
        if path == "/media":
            return self.serve_media(qs.get("p", [""])[0])
        if path == "/caption":
            cap, url = read_post_meta(urllib.parse.unquote(qs.get("p", [""])[0]))
            return self._send(200, json.dumps({"caption": cap, "url": url}).encode(),
                              "application/json")
        if path == "/status":
            with JOBS_LOCK:
                jobs_running = any(j["running"] for j in JOBS.values())
                jobs_payload = {k: {"running": v["running"], "log": v["log"][-20:]}
                                for k, v in JOBS.items()}
            payload = {"any": jobs_running or SCAN["running"],
                       "scan": dict(SCAN), "prewarm": dict(PREWARM),
                       "heartbeat": dict(HEARTBEAT), "jobs": jobs_payload}
            return self._send(200, json.dumps(payload).encode(), "application/json")
        return self._send(404, b"not found")

    do_HEAD = do_GET

    def do_POST(self):
        u = urllib.parse.urlparse(self.path)
        n = int(self.headers.get("Content-Length", 0))
        form = urllib.parse.parse_qs(self.rfile.read(n).decode() if n else "")
        if u.path == "/update":
            p = form.get("profile", [""])[0]
            if p and p in INDEX["profiles"]:
                if not (p in JOBS and JOBS[p]["running"]):
                    threading.Thread(target=run_update, args=([p],), daemon=True).start()
                return self._send(200, b'{"ok":true}', "application/json")
            return self._send(400, b'{"ok":false}', "application/json")
        if u.path == "/update-all":
            ps = [p for p in INDEX["profiles"]
                  if not (p in JOBS and JOBS[p]["running"])]
            threading.Thread(target=run_update, args=(ps,), daemon=True).start()
            return self._send(200, b'{"ok":true}', "application/json")
        if u.path == "/rescan":
            start_scan_thread(None)
            return self._send(200, b'{"ok":true}', "application/json")
        if u.path == "/heartbeat":
            if not HEARTBEAT["running"]:
                p = form.get("profile", [""])[0]
                names = [p] if (p and p in INDEX["profiles"]) else None
                start_heartbeat(names)
            return self._send(200, b'{"ok":true}', "application/json")
        if u.path == "/add":
            p = form.get("profile", [""])[0].strip().lstrip("@").lower()
            if p and re.match(r"^[a-z0-9._]{1,40}$", p):
                if not (p in JOBS and JOBS[p]["running"]):
                    # run_update downloads then scans the new profile into the index
                    threading.Thread(target=run_update, args=([p],), daemon=True).start()
                return self._send(200, b'{"ok":true}', "application/json")
            return self._send(400, b'{"ok":false}', "application/json")
        if u.path == "/account":
            ok = set_login(form.get("login", [""])[0])
            return self._send(200 if ok else 400,
                              b'{"ok":true}' if ok else b'{"ok":false}',
                              "application/json")
        return self._send(404, b"not found")

    def serve_thumb(self, rel):
        t = thumb_for(urllib.parse.unquote(rel))
        if not t or not t.exists():
            gif = (b"GIF89a\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\xff\xff\xff"
                   b"!\xf9\x04\x01\x00\x00\x00\x00,\x00\x00\x00\x00\x01\x00\x01"
                   b"\x00\x00\x02\x02D\x01\x00;")
            return self._send(200, gif, "image/gif")
        ctype = mimetypes.guess_type(str(t))[0] or "image/jpeg"
        return self._send(200, t.read_bytes(), ctype, {"Cache-Control": "max-age=86400"})

    def serve_media(self, rel):
        full = safe_under_root(urllib.parse.unquote(rel))
        if not full or not full.is_file():
            return self._send(404, b"not found")
        ctype = mimetypes.guess_type(str(full))[0] or "application/octet-stream"
        size = full.stat().st_size
        rng = self.headers.get("Range")
        if rng and rng.startswith("bytes="):
            try:
                s, _, e = rng[6:].partition("-")
                start = int(s) if s else 0
                end = int(e) if e else size - 1
                end = min(end, size - 1)
                start = max(0, min(start, end))
            except Exception:                         # noqa: BLE001
                start, end = 0, size - 1
            length = end - start + 1
            self.send_response(206)
            self.send_header("Content-Type", ctype)
            self.send_header("Accept-Ranges", "bytes")
            self.send_header("Content-Range", "bytes %d-%d/%d" % (start, end, size))
            self.send_header("Content-Length", str(length))
            self.end_headers()
            if self.command == "HEAD":
                return
            with open(full, "rb") as f:
                f.seek(start)
                remaining = length
                while remaining > 0:
                    chunk = f.read(min(65536, remaining))
                    if not chunk:
                        break
                    self.wfile.write(chunk)
                    remaining -= len(chunk)
            return
        self.send_response(200)
        self.send_header("Content-Type", ctype)
        self.send_header("Accept-Ranges", "bytes")
        self.send_header("Content-Length", str(size))
        self.end_headers()
        if self.command == "HEAD":
            return
        with open(full, "rb") as f:
            while True:
                chunk = f.read(65536)
                if not chunk:
                    break
                self.wfile.write(chunk)


class ThreadingServer(http.server.ThreadingHTTPServer):
    daemon_threads = True
    allow_reuse_address = True


def main():
    load_db_index()
    mimetypes.add_type("video/mp4", ".mp4")
    load_health()
    have_cache = load_index()
    if not have_cache:
        print("no cache yet — scanning the archive in the background (first run can take a while)…")
        start_scan_thread(None)
    else:
        start_prewarm()                              # warm thumbnails for instaloader profiles
    server = ThreadingServer((HOST, PORT), Handler)
    print("\n  offgram →  http://%s:%d" % (HOST, PORT))
    print("  collection: %s" % ROOT)
    print("  cache:      %s" % INDEX_FILE)
    print("  (Ctrl-C to stop)\n")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nbye")


if __name__ == "__main__":
    main()
